### ISSUE TITLE
Running on a remote machine (CORS related)

### ISSUE THREAD

**Issue by patricio-astudillo** [trypag/ohif-orthanc-postgres-docker#2]
Hi,

first of all nice work! Locally everything works like a charm. If I try to run it on a remote machine and access it through the ip address of that machine; I can access the pacs-admin page and pacs page. However, the viewer page does not load due to the following error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost/pacs/dicom-web/studies?limit=25&offset=0&fuzzymatching=false&includefield=00081030%2C00080060&StudyDate=19520218-20200730. (Reason: CORS request did not succeed)

I have tried to (first seperatly but also combined ):
- adapt the nginx.conf file (based on https://enable-cors.org/server_nginx.html). 
- change the server_name in the nginx.conf file to the address of the remote machine
- adapt the viewer.js file and replace localhost with the ip address of the remote machine
- disable the AuthenticationEnabled in the orthanc.json file
- use a different browser (firefox 78.0.2, Brave Version 1.9.72 and chrome Version 84.0.4147.89)

Am I missing something obvious here? It seams that the localhost in "http://localhost/pacs/dicom-web/studies?limit=25&offset=0..." does not refer to the ip address of the remote machine. Is this the intention? 

Thanks in advance for your time.

**Comment by patricio-astudillo** [comment]
I have resolved it myself so here is the solution:

The advise from https://enable-cors.org/server_nginx.html is solid, however in order to make everything work, I needed to add the 'always' keyword to the Access-Control-Allow-Origin header in the nginx.conf for the pacs reverse proxy.

```add_header 'Access-Control-Allow-Origin' '*' always;```

I also added this for GET and POST as follows:

```
if ($request_method ~* "(GET|POST)") {
          add_header 'Access-Control-Allow-Origin' '*' always;
        }
```

ps: the '*' is a bad idea...

Next, in order to be able to login to the pacs (due to the AuhenticationEnabled: true in orthanc.json), I needed to add the credentials of our 'demo' user (passw 'demo') in the header. I did this in the pacs reverse proxy in the nginx.conf as follows:

```
proxy_set_header Authorization "Basic ZGVtbzpkZW1v"; 
```

ps: the 'ZGVtbzpkZW1v' is demo:demo in base64.

And finally, I changed the server_name in the nginx.conf and the 'localhost' in the viewer.js file to the IP address of my remote machine.

As a bonus, I updated the viewer image to the latest version `ohif/viewer:v4.2.13.12114` which works like a charm and provides better error reports.

**Comment by trypag** [comment]
Hey @patricio-astudillo 

Congrats for solving your problem. Do you think your work could be relevant to other users ?
If so you can make a pull request and I will merge your improvements.

**Comment by trypag** [comment]
I don't get why it is required to add the password directly in the header, shouldn't you receive a prompt to fill in the credentials ? as in the local use case.

**Comment by bonviesinfo** [comment]
Hi @patricio-astudillo  do you succeed run without the CORS issuse?
because I follow your way to add the header of [ add_header 'Access-Control-Allow-Origin' '*' always;]
and the ohif still get black screen in 3 seconds.
what is your way to solve the problem? thanks

**Comment by dmd** [comment]
@patricio-astudillo I too tried your way and still just get a black screen. Do you think you could share your config?

@trypag Thanks for your repo, but I think as this ticket shows, it would be much more useful it it worked on a machine other than localhost!

**Comment by dmd** [comment]
@bonviesinfo did you ever manage to solve this?

**Comment by patricio-astudillo** [comment]
Dear Daniel Drucker,
I will try to look into this again and share my findings with you.
Best regards,
Patricio
Verstuurd vanaf mijn iPhone

**Comment by dmd** [comment]
I got it working!  It looks like I was just confused about what things to change (localhost SHOULD be changed to your real name) and what not to ('orthanc' should not, because that's the container name).

**Comment by patricio-astudillo** [comment]
Ah nice! Glad you got it working!

Verstuurd vanaf mijn iPhone
