### ISSUE TITLE
CORS error when running repo

### ISSUE THREAD

**Issue by OLI9292** [trypag/ohif-orthanc-postgres-docker#5]
Hey @trypag - thanks for putting this repo together. I am currently trying to setup OHIF + Orthanc.

After following the setup instructions: running `docker-compose up` and navigating to http://127.0.0.1:80/, I am seeing a CORS issue which is preventing OHIF from connecting to Orthanc (screenshot below).

<img width="585" alt="Screen Shot 2021-04-27 at 10 31 04 AM" src="https://user-images.githubusercontent.com/13812317/116259308-b10d0500-a743-11eb-96f3-faa6f8b661cd.png">

Is this something you've encountered? I have tried adding CORS headers to `nginx.conf` but unfortunately have not been able to fix the issue yet.

Thank you for your time.

**Comment by OLI9292** [comment]
I've just looked at closed issues and noticed a similar issue /issues/2 - I'm going to follow this thread for now.

**Comment by ekariz** [comment]
> Hey @trypag - thanks for putting this repo together. I am currently trying to setup OHIF + Orthanc.
> 
> After following the setup instructions: running `docker-compose up` and navigating to http://127.0.0.1:80/, I am seeing a CORS issue which is preventing OHIF from connecting to Orthanc (screenshot below).
> 
> <img alt="Screen Shot 2021-04-27 at 10 31 04 AM" width="585" src="https://user-images.githubusercontent.com/13812317/116259308-b10d0500-a743-11eb-96f3-faa6f8b661cd.png">
> 
> Is this something you've encountered? I have tried adding CORS headers to `nginx.conf` but unfortunately have not been able to fix the issue yet.
> 
> Thank you for your time.

http://localhost/   worked for me
